In [55]:
import numpy as np
import pandas as pd

In [56]:
df=pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [57]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [58]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [59]:
df['brand'].nunique()

32

### OneHotEncoding using pandas

In [60]:
pd.get_dummies(df,columns=['fuel','owner'], dtype = int,drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

## OneHotEncoding using Sklearn

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size = 0.2,random_state = 2)

In [62]:
x_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [63]:
from sklearn.preprocessing import OneHotEncoder

In [74]:
#here we have to take the operation just on the fuel and the owner one and then 
# we have to join it to the rest at last
ohe = OneHotEncoder(drop = 'first',sparse_output = False)

In [75]:
# fit and transform in one step only and the operation uses the sparce matric in the operatiion
# x_train_new = ohe.fit_transform(x_train[['fuel','owner']]).toarray() 
# when space is false the is will converted to array by itself
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [76]:
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [77]:
x_train_new

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], shape=(6502, 7))

In [78]:
# connect to all others
np.hstack((
    x_train[['brand','km_driven']].values
    ,x_train_new)).shape

(6502, 9)

## OneHotEncoder with Top Categories

In [80]:
count = df['brand'].value_counts()
count

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [81]:
df['brand'].nunique()
threshold = 100

In [83]:
repl = count[count <= threshold].index

In [87]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype = int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5890,0,0,0,0,0,0,1,0,0,0,0,0,0
2425,0,0,0,0,1,0,0,0,0,0,0,0,0
3346,0,0,0,0,0,0,0,0,0,0,0,0,1
6474,0,0,0,0,0,0,0,1,0,0,0,0,0
5921,0,0,0,0,0,0,0,0,0,0,0,1,0