In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/nietzs96/mnist-5k/mnist1.5k.csv

In [3]:
df = pd.read_csv('/kaggle/input/datasets/nietzs96/mnist-5k/mnist1.5k.csv')

In [4]:
df.head()

,Label,Pixel 1,Pixel 2,Pixel 3,Pixel 4,Pixel 5,Pixel 6,Pixel 7,Pixel 8,Pixel 9,...,Pixel 775,Pixel 776,Pixel 777,Pixel 778,Pixel 779,Pixel 780,Pixel 781,Pixel 782,Pixel 783,Pixel 784
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2, random_state=2)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [13]:
clf1 = LogisticRegression(max_iter=1000)
clf2= DecisionTreeClassifier()

In [14]:
clf1.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [15]:
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [16]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
print("Accuracy of Logistic Regression: ", accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Tree: ", accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression:  0.8966666666666666
Accuracy of Decision Tree:  0.7166666666666667

In [20]:
print("Logistic Regression Confusion Matrix \n")
pd.DataFrame(confusion_matrix(y_test,y_pred1), columns=list(range(0,10)))

Logistic Regression Confusion Matrix

    0   1   2   3   4   5   6   7   8   9
0  32   0   3   0   0   0   0   0   0   0
1   0  25   0   0   0   0   0   0   1   0
2   2   2  36   1   0   0   0   0   1   0
3   0   0   2  28   0   2   0   0   0   0
4   0   0   0   0  20   0   0   0   0   0
5   0   1   1   0   0  28   0   0   1   0
6   0   0   0   0   0   0  25   0   0   0
7   0   1   0   0   0   0   0  28   0   2
8   0   1   0   1   0   3   0   0  28   1
9   0   0   0   0   1   1   0   2   1  19

In [21]:
print("Decision tree Confusion Matrix \n")
pd.DataFrame(confusion_matrix(y_test,y_pred2), columns=list(range(0,10)))

Decision tree Confusion Matrix

    0   1   2   3   4   5   6   7   8   9
0  28   0   0   2   0   1   2   1   0   1
1   0  22   0   0   1   1   0   0   2   0
2   1   0  30   2   1   0   3   1   2   2
3   0   0   2  18   1   0   4   1   3   3
4   0   0   0   2  17   0   0   0   1   0
5   2   2   1   5   0  13   2   1   3   2
6   0   0   2   0   0   0  23   0   0   0
7   1   0   0   2   0   1   0  25   1   1
8   3   1   1   0   4   2   1   0  21   1
9   1   0   1   1   1   1   0   0   1  18

In [22]:
from sklearn.metrics import precision_score,recall_score,f1_score
precision_score(y_test,y_pred1,average='weighted')

0.8982071555895086

In [23]:
print(recall_score(y_test,y_pred1,average='weighted'))
print(f1_score(y_test,y_pred1,average='weighted'))

0.8966666666666666
0.896449184215907

In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.94      0.91      0.93        35
           1       0.83      0.96      0.89        26
           2       0.86      0.86      0.86        42
           3       0.93      0.88      0.90        32
           4       0.95      1.00      0.98        20
           5       0.82      0.90      0.86        31
           6       1.00      1.00      1.00        25
           7       0.93      0.90      0.92        31
           8       0.88      0.82      0.85        34
           9       0.86      0.79      0.83        24

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300