In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/uciml/iris/Iris.csv
/kaggle/input/datasets/uciml/iris/database.sqlite

In [7]:
df = pd.read_csv('/kaggle/input/datasets/uciml/iris/Iris.csv')

In [8]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Species'] = encoder.fit_transform(df['Species'])

In [13]:
df.sample(10)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
116  117            6.5           3.0            5.5           1.8        2
36    37            5.5           3.5            1.3           0.2        0
90    91            5.5           2.6            4.4           1.2        1
75    76            6.6           3.0            4.4           1.4        1
128  129            6.4           2.8            5.6           2.1        2
53    54            5.5           2.3            4.0           1.3        1
138  139            6.0           3.0            4.8           1.8        2
66    67            5.6           3.0            4.5           1.5        1
71    72            6.1           2.8            4.0           1.3        1
121  122            5.6           2.8            4.9           2.0        2

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2, random_state=2)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [19]:
clf1 = LogisticRegression(max_iter=10000)
clf2 = DecisionTreeClassifier()

In [21]:
clf1.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [22]:

clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [23]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression: ", accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Tree: ", accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression:  1.0
Accuracy of Decision Tree:  1.0

In [30]:
print("Logistic Regressio Confusion Matrix \n")
pd.DataFrame(confusion_matrix(y_test,y_pred1), columns=list(range(0,3)))

Logistic Regressio Confusion Matrix

    0  1  2
0  14  0  0
1   0  8  0
2   0  0  8

In [31]:
print("Decision Tree Confusion Matrix \n")
pd.DataFrame(confusion_matrix(y_test,y_pred2), columns=list(range(0,3)))

Decision Tree Confusion Matrix

    0  1  2
0  14  0  0
1   0  8  0
2   0  0  8

In [34]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic prediction'] = y_pred1
result['Decision predicion'] = y_pred2

In [35]:
result.sample(5)

     Actual Label  Logistic prediction  Decision predicion
54              1                    1                   1
12              0                    0                   0
125             2                    2                   2
35              0                    0                   0
45              0                    0                   0

In [36]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_pred1,average=None)

array([1., 1., 1.])