In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2,random_state=2)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [10]:
clf1 = LogisticRegression(max_iter=10000)
clf2 = DecisionTreeClassifier()

In [12]:
clf1.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [13]:

clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [14]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy score of Logistic Regression: ", accuracy_score(y_test,y_pred1))
print("Accuracy score of Decision Tree: ", accuracy_score(y_test,y_pred2))

Accuracy score of Logistic Regression:  0.848780487804878
Accuracy score of Decision Tree:  0.9804878048780488

In [16]:
confusion_matrix(y_test,y_pred1)

array([[81, 24],
       [ 7, 93]])

In [17]:
print("Logistic Regression Confusion Matrix \n")
pd.DataFrame(confusion_matrix(y_test,y_pred1), columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  81  24
1   7  93

In [19]:
print("Decision Tree Confusion Matrix \n")
pd.DataFrame(confusion_matrix(y_test,y_pred2), columns=list(range(0,2)))

Decision Tree Confusion Matrix

     0    1
0  101    4
1    0  100

In [20]:
result = pd.DataFrame()
result["Actual Label"] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [21]:
result.sample(8)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
456             0                               1                         0
639             1                               1                         1
817             1                               1                         1
593             0                               0                         0
854             0                               1                         0
600             0                               1                         0
549             1                               1                         1
846             1                               1                         1

In [22]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [25]:
print("for Logistic regression Model")
print("-"*50)     #--------------------------------------------------
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1), columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ", precision_score(y_test,y_pred1))
print("Recall - ", recall_score(y_test,y_pred1))
print("F1 - ", f1_score(y_test,y_pred1))

for Logistic regression Model
--------------------------------------------------
    0   1
0  81  24
1   7  93
--------------------------------------------------
Precision -  0.7948717948717948
Recall -  0.93
F1 -  0.8571428571428571

In [26]:
print("for Decision Tree Model")
print("-"*50)     #--------------------------------------------------
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2), columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ", precision_score(y_test,y_pred2))
print("Recall - ", recall_score(y_test,y_pred2))
print("F1 - ", f1_score(y_test,y_pred2))

for Decision Tree Model
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision -  0.9615384615384616
Recall -  1.0
F1 -  0.9803921568627451

In [27]:
print(precision_score(y_test,y_pred1,average=None))
print(precision_score(y_test,y_pred2,average=None))
print(recall_score(y_test,y_pred2,average=None))

[0.92045455 0.79487179]
[1.         0.96153846]
[0.96190476 1.        ]